### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by conceptfarm** [conceptfarm/Poliigon-Asset-Browser#1]
- [ ] maxscript -> resolution choice drop down
- [ ] browser -> grab assets in all resolutions available
- [ ] function for creating multiple resolutions for downloaded assets, proper naming and directory structure (1k, 3k, 4k)
